In [3]:
import torch

item2idx = torch.load("./item2idx.pt")

/tmp/ipykernel_2243062/3029161825.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  item2idx = torch.load("./item2idx.pt")


In [4]:
import torch

detail2idx = torch.load("./detail2idx.pt")

/tmp/ipykernel_2243062/147671449.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  detail2idx = torch.load("./detail2idx.pt")


In [5]:
len(item2idx)

60233

In [6]:
import pandas as pd

item_ids = list(item2idx.keys())

In [7]:
item_data = pd.read_csv("./articles.csv")


In [8]:
item_data[item_data.article_id.isin(item_ids)].detail_desc.nunique()

26235

In [9]:
unique_desc = item_data[item_data.article_id.isin(item_ids)]["detail_desc"].unique()

In [10]:
unique_desc_dict = {v:k for k,v in enumerate(unique_desc)}

In [11]:
temp = item_data[item_data.article_id.isin(item_ids)]
temp["detail_idx"] = temp["detail_desc"].map(unique_desc_dict)

/tmp/ipykernel_2243062/1330530338.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["detail_idx"] = temp["detail_desc"].map(unique_desc_dict)


In [12]:
temp["item_idx"] = temp["article_id"].map(item2idx)

/tmp/ipykernel_2243062/36583869.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["item_idx"] = temp["article_id"].map(item2idx)


In [13]:
temp = temp[["article_id", "item_idx","detail_desc", "detail_idx"]]

In [14]:
temp.columns

Index(['article_id', 'item_idx', 'detail_desc', 'detail_idx'], dtype='object')

In [15]:
# unique_prompt = unique_desc + "Displayed against a white background, ensuring the entire item is visible and centrally placed. No one wears it."
# unique_prompt = unique_desc + " Displayed on a plain, light-colored background with soft lighting to highlight details. The item is centered and fully visible from a single perspective, without any people or models. No additional elements are in the background, ensuring the product is the sole focus."
# unique_prompt = unique_desc + " Displayed on a clean, plain white background with bright, even lighting to fully illuminate the product. The item is perfectly centered and completely visible, shown from its most flattering angle. No models, mannequins, or people are present. No shadows or extra elements are visible, ensuring the product is the only object in the frame, presented like a professional product display."
# unique_prompt = unique_desc + " Only the described product is displayed, shown on a plain white background with bright, even lighting to ensure clear visibility. The item is isolated and centered, fully visible, and presented from its most flattering angle. Absolutely no people, models, mannequins, or additional objects are included in the image. The focus is solely on the product, with no shadows, reflections, or extra elements—just the single item, as in a professional product listing."

In [16]:
# torch.save(list(unique_prompt), "./small_uni_enhanced_prompt3.pt")

In [17]:
# s_uni_prom_dict = {k:v for k,v in enumerate(list(unique_prompt))}
# torch.save(s_uni_prom_dict, "./s_uni_enhanced_prom3_dict.pt")

In [18]:
# !huggingface-cli login --token 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 

In [42]:
from datetime import datetime
from huggingface_hub import HfApi
import os


def mk_dir(file_path):
    if not os.path.exists(file_path):
        os.makedirs(file_path)

def get_timestamp(date_format: str = '%d%H%M%S') -> str:
    timestamp = datetime.now()
    return timestamp.strftime(date_format)

data_dir = "./data/sequential/amazon_origin"
mk_dir(data_dir)

_, _, repo, dir = data_dir.split("/")
api = HfApi()


In [20]:
from huggingface_hub import snapshot_download
data_repo = "sequential"
dataset = "small"
data_version = "14ae401637b5bcce0c33016d928a9a7e85741ee5"


path = (
            snapshot_download(
                repo_id=f"SLKpnu/{data_repo}",
                repo_type="dataset",
                cache_dir="./data",
                revision=data_version,
            )
            + "/"
            + dataset
        )

/home/chanmi/anaconda3/envs/frec/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 43 files: 100%|██████████| 43/43 [00:00<00:00, 25961.58it/s]


In [21]:
import torch 

emb_path = "../dataset_fashion/embeddings"

gen_emb = torch.load(f'{path}/gen_img_emb.pt')
ori_emb = torch.load(f'{path}/origin_img_emb.pt')

/tmp/ipykernel_2243062/1515141994.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  gen_emb = torch.load(f'{path}/gen_img_emb.pt')
/tmp/ipykernel_2243062/1515141994.py:6: 

In [22]:
from tqdm import tqdm
n_desc = 26235
new_gen_emb = [[] for _ in range(n_desc)]

for i in tqdm(range(n_desc)):
    new_gen_emb[i] = torch.load(f'{emb_path}/{i}.pth')


  0%|          | 0/26235 [00:00<?, ?it/s]/tmp/ipykernel_2243062/3693323434.py:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  new_gen_emb[i] = torch.load(f'{emb_path}/{i}.p

In [23]:
new_gen_emb = torch.tensor(new_gen_emb)

/tmp/ipykernel_2243062/2182959508.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)
  new_gen_emb = torch.tensor(new_gen_emb)


In [24]:
gen_emb = gen_emb.repeat(1,2,1)

In [25]:
gen_emb.shape

torch.Size([60233, 6, 512])

In [26]:
for _, ele in tqdm(temp.iterrows(), total=len(temp)):
    gen_emb[ele["item_idx"]] = torch.concat((gen_emb[ele["item_idx"]][:3], new_gen_emb[ele["detail_idx"]]))

100%|██████████| 60233/60233 [00:02<00:00, 20233.06it/s]


In [27]:
new_gen_emb[0]

tensor([[ 0.1852,  1.0894, -0.5514,  ...,  0.1480, -0.0098, -0.2518],
        [ 0.2704, -1.0512, -0.8787,  ...,  0.4758,  0.1346, -0.3790],
        [ 0.1008, -0.3619,  0.0370,  ...,  0.2870,  0.2180,  0.0423]])

In [28]:
gen_emb[0]

tensor([[ 0.4264,  0.3780,  0.3853,  ...,  0.5982,  0.2949, -0.1096],
        [ 0.6635,  0.5555, -0.0092,  ...,  0.3135, -0.0543,  0.0335],
        [ 0.3004,  0.2246, -0.1604,  ...,  0.0969,  0.1987, -0.0343],
        [ 0.1852,  1.0894, -0.5514,  ...,  0.1480, -0.0098, -0.2518],
        [ 0.2704, -1.0512, -0.8787,  ...,  0.4758,  0.1346, -0.3790],
        [ 0.1008, -0.3619,  0.0370,  ...,  0.2870,  0.2180,  0.0423]])

In [29]:
# torch.save(gen_emb, f"./six_gen_emb_241014.pt")

In [30]:
ori_emb[0].shape

torch.Size([512])

In [31]:
ori_emb_tensor = torch.zeros_like(gen_emb[:,1,:])

In [32]:
ori_emb_tensor.shape

torch.Size([60233, 512])

In [33]:
for k,v in tqdm(ori_emb.items()):
    ori_emb_tensor[k] = v

100%|██████████| 60233/60233 [00:00<00:00, 577506.72it/s]


In [34]:
ori_emb_tensor

tensor([[ 0.4905,  0.6375,  0.3106,  ..., -0.0124,  0.1379, -0.1154],
        [ 0.5238,  0.7029, -0.1322,  ..., -0.1095,  0.4196, -0.3097],
        [ 0.3400,  0.6079,  0.0885,  ...,  0.1545,  0.0346, -0.0413],
        ...,
        [ 0.4439,  0.0407,  0.0661,  ...,  0.4365, -0.0886,  0.0384],
        [ 0.5105, -0.2009,  0.3272,  ...,  0.2940, -0.0759,  0.0587],
        [ 0.3958,  0.4081,  0.2695,  ...,  0.3067,  0.3968, -0.0345]])

In [35]:
gen_emb.shape

torch.Size([60233, 6, 512])

In [36]:
ori_emb_tensor.shape

torch.Size([60233, 512])

In [37]:
cos = torch.nn.CosineSimilarity(dim=1)
input_img = []

for i in tqdm(range(gen_emb.shape[0])):
    gen_i_emb = gen_emb[i,:,:]
    ori_i_emb = ori_emb_tensor[i]
    
    input_img.append(torch.argsort(cos(ori_i_emb,gen_i_emb), descending=True)[0])



100%|██████████| 60233/60233 [00:01<00:00, 44276.59it/s]


In [38]:
# torch.save(torch.tensor(input_img, dtype=torch.int8), f"./input_gen_img.pt")

In [39]:
print(1+'0')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [41]:
torch.save(ori_emb_tensor, f'./ori_emb_tensor.pt')

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# cos = torch.nn.CosineSimilarity(dim=1)
cos = cosine_similarity
sim_item_gen_img_inner = []
sim_item_gen_img_outter = []
step = 20000

for outter in range(0,gen_emb.shape[0], step):
    gen_outter = gen_emb[outter:outter+step,:,:]
    for inner in tqdm(range(6)):
        gen_inner = gen_outter[:,inner,:]
        cos_mat = cos(gen_inner,ori_emb_tensor) # step X n_item
        np.fill_diagonal(cos_mat,0) # self_sim remove

        sim_item_gen_img_inner.append(torch.argsort(torch.tensor(cos_mat), dim=1 ,descending=True)[:,0])
    sim_item_gen_img_outter.append(torch.stack(sim_item_gen_img_inner, dim=1))



In [58]:
data_dir = './img_gen/hm_small'

In [ ]:
_, repo, dir = data_dir.split("/")
api = HfApi()
api.upload_folder(folder_path=data_dir, path_in_repo=dir, repo_id=f"SLKpnu/{repo}", 
                  commit_message=f"dataset created timestamp : {get_timestamp()}", repo_type="dataset")

In [48]:
ttt = [torch.zeros(size=(2000,6)) for _ in range(3)]

In [55]:
torch.concat(ttt, dim=0).shape

torch.Size([6000, 6])